// 所有实际资料都在这里维护。图片放在 public/images/，路径填 /images/文件名。
export const site = {
  name: 'NanoCamp',
  url: 'https://nanocamp-community.zjun27256.chatgpt.site/',
  slogan: 'Meet. Build. Make something together.',
  chineseSlogan: '让有趣的人相遇，让相遇的人一起创造。',
  description: 'NanoCamp 是一个面向跨专业学生的创造者社区。从 minicamp 黑客松开始，让有趣的人相遇，一起把想法做出来。',
  logo: '/images/nanocamp-wordmark.png',
  symbol: '/images/nanocamp-symbol.png',
  // 原图保留不变，以下矩形只控制网页显示范围：[x, y, 宽, 高, 原图宽]。
  logoCrop: [48, 438, 1170, 290, 1254],
  signatureCrop: [48, 438, 1170, 355, 1254],
  join: { qrCode: null, contact: null, contactLabel: '联系社区', description: '和有好奇心的伙伴，一起开始。' },
};

export const event = {
  title: '首届 minicamp',
  edition: '01',
  date: null,
  location: null,
  theme: null,
  status: '已结束',
  intro: '一场黑客松，是一次相遇的开始。活动告一段落，一起创造的故事还在继续。',
  summary: [],
  cover: null,
};

// 作品数据由 scripts/sync-minicamp-projects.mjs 从 minicamp 官方接口整理而来（首届 minicamp，2026）。
// slug 决定详情页地址 /projects/<slug>/，填写后应尽量保持稳定。
// 外部地址必须是完整 http 或 https；缺失字段保持 null，页面会显示「待补充」而不是编造内容。
export const projects = [
{
    id: '01', slug: 'aiclassrep', title: 'AIClassRep',
    description: 'AI 课代表：连接本机 QQ 群，自动监听群消息，用 AI 提取课程通知、作业、考试和调课信息，整理成可搜索、可提醒的个人课代表。',
    problem: '大学生的重要通知分散在多个 QQ 群里，消息数量多、时间线混乱，容易错过上课安排、作业截止时间、考试通知和临时调课。通知还经常被修改、撤回或补充，人工整理成本高，很难持续维护一份准确的日程。', solution: 'AIClassRep 连接用户本机运行的 QQ 与群聊，仅监听用户主动开启的群，把新消息交给 AI 提取为结构化事件。系统会识别课程、时间、地点、作业、考试、改期和取消等信息，并保留原始消息作为依据；当同一事件发生修改或取消时，自动更新原安排，避免重复记录。  \n用户可以在网页中查看今日安排、课程表、待办和事件详情，也可以导入教务系统课表或 XLS 文件。所有数据保存在本地，适合个人使用，减少隐私和部署成本。',
    theme: 'Build for Humans', team: 'TEAM 01', year: '2026',
    tools: ['Codex', 'Claude Code', 'DeepSeek Harness', 'Devin'], members: [{ name: '杨智杰', role: '后端骨架与业务API' }, { name: '宋卓洋', role: '采集端与打包' }, { name: '朱霏钒', role: '前端开发' }, { name: '李银', role: 'AI流水线' }, { name: '战畅', role: 'Idea提供、路演展示' }],
    cover: '/images/projects/aiclassrep.jpg', coverAlt: 'AIClassRep 作品封面', coverFull: null,
    repoUrl: 'https://github.com/wahha696/Minicamp-AIClassRep', demoUrl: null,
    sourceId: 'PROJECT-7705461CF0',
  },
  {
    id: '02', slug: 'project-02', title: '校园雷达',
    description: '为学校决策者/领导者汇总并解决各个平台上出现的衣食住行问题',
    problem: '学生的小问题散在社媒里没人管，学校想改却很难收集汇总不同平台消息源，且领导者需费心考量；这个项目想用"公开信息找问题 + 现有资源重排出方案 + 处理结果留档"把这条链闭合起来', solution: '输入校区名即可联网检索公开信息，按吃、住、行、生活服务四类筛选出可归属该校区的问题，每条绑定原文链接可追溯；问题按类别落到校区地图上，用红黄绿显示集中程度，点击跳转对应清单；系统按问题类型只能生成整改方案，固定包含牵头部门、存量资源、三步动作和复测指标。学生可提交反馈，处理后标记已解决并持久保存，形成闭环。',
    theme: 'Build for Humans', team: 'TEAM 02', year: '2026',
    tools: ['Codex', 'Claude Code', 'DeepSeek Harness'], members: [{ name: '李熙言', role: '产品负责人、优化完善' }, { name: '黄嘉莹', role: '视觉设计、提出建议' }, { name: '关添予', role: '后端开发、前端开发' }, { name: '肖佳兴', role: '前端开发、技术支持' }, { name: '张鹏辉', role: '后端开发、技术支持' }],
    cover: null, coverAlt: '校园雷达 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-F46ED0A7A6',
  },
  {
    id: '03', slug: 'build-to-taste-light-of-yuelu', title: 'Build to Taste：报寝助手 × 麓光 · Light of Yuelu',
    description: '用自动化解决生活部每晚的报寝，用 HD-2D 像素游戏还原中南大学的来路。',
    problem: '【报寝助手】将生活部每晚要统计全年级是否回寝的繁琐流程自动化。\n\n【麓光· Light of Yuelu】使用HD-2D像素短篇重现中南大学从 1914 年湘雅到 2000 年三校合并的百年来路。\n\n这两种方案呼应了第一天的Build to Taste', solution: '【报寝助手】免登录的手机填报网页，人数合计自动核对；值班干事审核、补录后一键“通过并发送”，审过哪一版就发哪一版。技术栈：Python / FastAPI / SQLite、openpyxl、QQ 机器人（NapCat / OneBot），已部署上线。9 月 26 日在自动化学院 24 级首次实战：19 个班数据全齐（18 班副班长自主提交、1 班补录），23:05 审核定版；自动群发已在测试群跑通。\n\n【麓光】约 8～9 分钟的 HD-2D 像素横版短篇：跟随一缕“麓光”，走过 1914 湘雅、1952 矿冶、1960 铁道、2000 三校合并，四章对应校风“向善、求真、唯美、有容”，终章在全 3D 的岳麓山校区正门落在校训“知行合一，经世致用”。游戏不用一张图片素材，画面、角色、配乐全部由代码生成（three.js + 自研 HD-2D 光影管线，约 4.4 万行代码，6 首代码合成的原创配乐）；史实检索 166 个来源交叉核验。提供网页版与 Windows 离线版。',
    theme: 'Build for Humans', team: 'TEAM 04', year: '2026',
    tools: ['Claude Code', 'Codex'], members: [{ name: '罗景涛', role: null }, { name: '鲍渐', role: null }, { name: '田鑫源', role: null }, { name: '郭亿瑞', role: null }],
    cover: '/images/projects/build-to-taste-light-of-yuelu.jpg', coverAlt: 'Build to Taste：报寝助手 × 麓光 · Light of Yuelu 作品封面', coverFull: null,
    repoUrl: null, demoUrl: 'https://zhigao.me/#projects',
    sourceId: 'PROJECT-D032B16A92',
  },
  {
    id: '04', slug: 'supernote', title: 'SuperNote',
    description: '笔记协同与多模态笔记输入输出',
    problem: '网课学习的核心矛盾不是信息不足，而是内容难以被再次调用。', solution: '多模态笔记输入输出与整理',
    theme: 'Build for Humans', team: 'TEAM 05', year: '2026',
    tools: ['DeepSeek', 'ChatGPT', 'Claude Code'], members: [{ name: '康智翔', role: '产品负责人' }, { name: '曾祥源', role: '架构设计' }, { name: '郭柱', role: '前端开发' }, { name: '周昭成', role: 'AI ENGNEER' }, { name: '张力文', role: '后端开发' }],
    cover: null, coverAlt: 'SuperNote 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-F0D4B25ACF',
  },
  {
    id: '05', slug: 'project-05', title: '收藏夹不吃灰计划',
    description: '防止收藏夹里的链接和视频吃灰',
    problem: '用户在抖音、B站、微信公众号等平台浏览时，经常会收藏大量有价值的视频、图文内容，但收藏后容易长期“吃灰”。传统收藏方式存在内容分散、难以检索、缺乏整理和关联等问题；如果依靠人工观看、总结和打标签，又需要投入大量时间，尤其面对跨平台、大量碎片化信息时效率较低。同时，现有知识管理工具与内容平台之间缺乏自动化连接，用户很难将收藏内容真正转化为可长期检索、复用的个人知识。', solution: '我们设计了一套AI驱动的跨平台内容收藏与个人知识库系统。用户只需在手机或电脑端提交视频或内容链接，系统即可自动完成内容获取、文字与图像信息提取、AI总结、分类与关键词生成，并将结果同步至本地 Obsidian 知识库。手机端与电脑端通过云端数据中心进行实时同步，同时保留本地数据，实现跨设备访问与本地长期保存。\n在此基础上，系统还可根据笔记之间的标签、双向链接及语义关系生成可视化知识网络，使零散收藏逐渐形成相互关联的个人知识体系，帮助用户实现从“收藏内容”到“沉淀知识、快速检索和再次利用”的转变。',
    theme: 'Build for Humans', team: 'TEAM 06', year: '2026',
    tools: ['Claude', 'DeepSeek Harness', 'Codex', 'WorkBuddy'], members: [{ name: '于政霖', role: '产品负责人，负责想法设计、后端开发、前端功能联结' }, { name: '路和鑫', role: '前端开发主力，将系统转化为可视化界面' }, { name: '刘森', role: '前端功能补充与完善' }, { name: '段旭冉', role: '手机端前端开发与设计' }],
    cover: '/images/projects/project-05.jpg', coverAlt: '收藏夹不吃灰计划 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-27F2D9B0F8',
  },
  {
    id: '06', slug: 'project-06', title: '念图',
    description: '将混乱的想法结构化，并提出一个可以立刻执行的解决方法',
    problem: '将混乱的想法结构化，并提出一个可以立刻执行的解决方法', solution: '念图（NianMap）​ 是一款面向“启动前混乱期”的 AI 工具。它解决的问题是：想法很多却无法行动。用户想到哪写到哪直接输入，念图自动将表达整理为四类节点——目的、资源、行动、卡点，并保留原文供回溯；AI 进而提出想法间的联系线索，最终给出一个 10–30 分钟即可完成的第一步小行动，让开始有路。',
    theme: 'Build for Humans', team: 'TEAM 07', year: '2026',
    tools: ['Codex'], members: [{ name: '刘梓婵', role: '负责人，前端开发' }, { name: '智琪童', role: '策划' }, { name: '刘尹轩', role: '后端开发' }],
    cover: '/images/projects/project-06.jpg', coverAlt: '念图 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-6ACC3D7CC7',
  },
  {
    id: '07', slug: 'project-07', title: '中南人的课表应用',
    description: '为了解决wakeup过于臃肿并且中南e行寄了，大家查看课表不方便而设计的',
    problem: '中南e行寄了，用不了了；wakeup时不时的开屏广告总是把我们硬控，页面中的和应用中内嵌的广告套件很烦人，导入课程表的脚本会总是不适配官网可课表结构。所以一个快捷轻量化的课表软件非常必要', solution: '针对中南大学学生查看和管理课程不便、手动录入课表耗时、教务系统信息不易长期保存以及无法在手机桌面快速查看课程等问题，本项目开发了“拾光课程表·中南”Android 应用。\n本应用适配中南大学教务系统，用户登录后即可一键导入课程名称、教师、上课地点、上课周次和节次等信息，避免逐门手动录入。应用提供今日课表和周课表视图，帮助用户快速了解当天及整周的课程安排；支持课程编辑、课程提醒和桌面小组件，用户无需打开教务系统或应用即可查看近期课程；同时支持 JSON 课表备份恢复和 ICS 日历导出，降低课程数据丢失风险，并方便与其他日历应用配合使用。\n此外，应用支持深色模式、课程颜色和课表样式自定义，能够适应不同用户的使用习惯。项目采用开源方式维护，针对中南大学教务系统进行了专门适配，具有较强的实用性、可维护性和推广价值。',
    theme: 'Build for Humans', team: 'TEAM 13', year: '2026',
    tools: ['Codex', 'WorkBuddy', 'DeepSeek Harness', 'CC Switch'], members: [{ name: '贺俊豪', role: null }, { name: '徐惠翔', role: null }, { name: '王泽胤', role: null }, { name: '王健琨', role: null }],
    cover: '/images/projects/project-07.jpg', coverAlt: '中南人的课表应用 作品封面', coverFull: null,
    repoUrl: 'https://github.com/GaLeKu/shiguangschedule-csu', demoUrl: null,
    sourceId: 'PROJECT-8A88AA6838',
  },
  {
    id: '08', slug: 'project-08', title: '多人格圆桌会谈',
    description: '给想听多方观点、又没有合适讨论伙伴的人，让几个性格和立场不同的 AI 角色围坐一桌，陪你闲聊、帮你辩清问题、分工完成项目设计。',
    problem: '1.一个人想事情时，常常只从自己的角度出发，缺少反对意见，也没人帮着查漏补缺。组织真人讨论成本很高：要约时间、凑人，气氛也不一定放得开。普通 AI 聊天又只有一个声音，回答容易四平八稳、附和用户，很难看到真正的分歧。\n2.一个人无聊的时候想看看不同人格或者说是不同人在一起讨论是什么场景，可以去供人们娱乐。\n3.这个项目还可以帮你去解决搭建项目的问题，比如说你想搭建一个项目，可以给你这些项目进行分工，然后给出明确的建议帮助AI小白更好的去使用AI搭建项目。\n4.帮助人们排解心中的疑惑解决情感上的问题。\n5.总的说，这个项目既可以用来娱乐，也可以用来辩论，也可以用来解决问题。', solution: '1. 选模式、定主题、选场景。\n   - 娱乐：闲聊、角色扮演、脑洞接龙。流程是开场破冰、脑洞接龙、投票收尾。\n   - 辩论：分正反方立论、交锋质询、总结陈词，最后给出双方的共识和分歧。\n   -情感分析：进行情感分析，同时分析事实，然后安慰他人或者是给出解决方案\n   - 工作 · 创造项目：负责人拆分任务，几个工作 Agent 分工、交接、复核，最后产出网站、App 或设计方案。\n   - 场景有三个：圆桌会议室、辩论室和办公室。\n2. 选人物。 每个人物有自己的职业背景、知识领域、价值观、说话风格和行为边界。用户可以为这一次讨论选择人物性格，比如冷幽默、直接、怀疑，但不会改动人物的公共设定。\n3. 观看或参与讨论。 人物按讨论引擎安排轮流发言，发言边生成边显示。用户可以随时插话、点名某个人物回答，也可以随时停止。讨论结束后，系统会整理出总结、共识、分歧和结论。\n四个模式各用一套讨论引擎，分别由不同成员负责，参数都可以调节。所有人物共用同一个大模型接口，只靠不同的人物设定来表现出不同性格。人物用统一的 JSON 格式描述，放进人物库就会自动加载，并经过格式校验。以后新增人物时不需要改代码。可以根据自己的喜好选场景或者添加人物.',
    theme: 'Build for Humans', team: 'TEAM 17', year: '2026',
    tools: ['Claude Code'], members: [{ name: '冷嘉昌', role: '负责情感分析与工作创造项目的人物设计还有引擎设计' }, { name: '裴航', role: '负责娱乐项目的人物设计还有引擎设计' }, { name: '杨育民', role: '负责前端设计和交互' }, { name: '黄向石', role: '负责辩论项目的人物设计还有引擎设计' }],
    cover: '/images/projects/project-08.jpg', coverAlt: '多人格圆桌会谈 作品封面', coverFull: null,
    repoUrl: 'https://github.com/Maxworkinghard/muti-agent', demoUrl: null,
    sourceId: 'PROJECT-575A59466B',
  },
  {
    id: '09', slug: 'memodot', title: 'MemoDot',
    description: '为想随时记录代办事件和灵感的人设计的随身记',
    problem: '人们在日常生活和工作中经常通过语音记录灵感、任务和提醒，但录音内容难以整理、搜索和回顾，容易遗漏重要事项。用户需要手动转写和分类，耗时较长，也无法方便地从一段话中提取多个待办事项及其时间、地点等信息。', solution: 'PocketMemory-AI 接收本地音频或 StickS3 硬件录音，先通过 SenseVoiceSmall 进行中文语音识别，再调用大模型对文本进行结构化分析，自动提取摘要、任务、时间、地点、相关人物、标签和意图等信息。系统将结果保存到本地数据库，并提供 FastAPI 接口和网页界面，支持历史记录查看、关键词搜索以及带时间任务的提醒功能。',
    theme: 'Build for Humans', team: 'TEAM 18', year: '2026',
    tools: ['Codex', 'DeepSeek'], members: [{ name: '孟萍', role: 'UI设计' }, { name: '刘梦颖', role: 'Debug' }, { name: '陈铭君', role: '后端' }, { name: '毛雨湘', role: '硬件设计' }],
    cover: '/images/projects/memodot.jpg', coverAlt: 'MemoDot 作品封面', coverFull: null,
    repoUrl: 'https://github.com/cmj665/MemoDot.git', demoUrl: null,
    sourceId: 'PROJECT-B6B5B252C4',
  },
  {
    id: '10', slug: 'project-10', title: '中南大学校园出行与充电',
    description: '充电问题，交警安全，二手电动车审核交易',
    problem: '找不到充电位，避免因为不小心违规而被处罚', solution: '以app查询',
    theme: 'Build for Humans', team: 'TEAM 19', year: '2026',
    tools: [], members: [{ name: '陈双', role: '负责人，前端' }, { name: '程垚彬', role: '前端后端' }, { name: '张书玮', role: null }, { name: '田祎轩', role: null }, { name: '朱亮宇', role: null }],
    cover: null, coverAlt: '中南大学校园出行与充电 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-6077DFFEC6',
  },
  {
    id: '11', slug: 'csu-online-game', title: 'CSU Online game',
    description: '这是一个"披着游戏外衣的校园生存模拟器"，用沙雕文案和真实校园梗，把大学生的焦虑变成一个可以笑着玩下去的东西。',
    problem: '大学生每天都要面对早八起不来、期末考到崩、小组作业遇猪队友、体测跑不动、查寝被突击这些真实又持续的压力，但生活里没有轻松的出口，努力和躺平都没人看见；每天走同一条路、吃同一家食堂，四年下来却说不清"自己的大学生活到底是什么样的"；明明室友就坐在旁边，却各玩各的手机，想一起玩一下却被注册、下载、加速器拦住；市面上的校园 App 又都在解决功能问题，没有一个人问你"今天过得怎么样"——说到底，大学生最需要的不是"帮我做这件事"，而是理解我、陪我笑、让我觉得这四年没白过。', solution: '我们不做工具，而是做一个"能陪你笑着活下去的校园生存模拟器"：玩家从签收录取通知书开始，选一种生存流派（卷王/摆烂/摸鱼/社交），分配初始属性，进入 10 章剧情主线（大一到大四），每章通过"看剧情 → 做选择 → 属性实时变化"推进，途中会随机遭遇校园随机事件和四大 BOSS（早八诅咒、期末清算、小组作业囚徒、体测噩梦），属性归零会触发死亡和多选复活机制，第 10 章结算时根据四年选择触发四种终极结局之一；关键功能包括剧情主线、生存流派、六项属性（绩点/心态/体力/钱包/人缘/作息）、死亡复活、BOSS 战、随机事件、14 项成就与 4 种结局、本机双人互助、校园漫游地图、长沙天气魔法系统和生存手册，核心是用沙雕文案消解真实校园压力，让每个中南人都能在里面看到自己，笑一下，然后继续活下去。',
    theme: 'Reimagine Campus', team: 'TEAM 03', year: '2026',
    tools: ['Codex', 'DeepSeek', 'ChatGPT'], members: [{ name: '舒清瑶', role: '产品负责人' }, { name: '徐传奇', role: '前端开发' }, { name: '王如怡', role: '视觉设计' }, { name: '邹艾融', role: '产品负责人' }],
    cover: '/images/projects/csu-online-game.jpg', coverAlt: 'CSU Online game 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-CD3953B64C',
  },
  {
    id: '12', slug: 'project-12', title: '电动车大学跑路app',
    description: '为中南大学学生解决上下学被堵在路上的问题',
    problem: '1. 早晚高峰“全都要挤同一条路”\n室友宿舍、教学楼扎堆，上下课时间又高度重合，几千人同时从一个片区涌向另一片，主干道、生活区走廊被塞满。大家只能凭感觉走，常常集体堵在同一条路。\n\n2. “哪里堵”没人提前告诉你\n校园不像城市有实时导航，堵不堵全靠到眼前才知道。等你走到那里，队伍已经排成长龙，只能跟着堵。\n\n3. 天气、封路、突发事件会“临时大变样”\n下雨天车速慢、人流更密集；某段路施工封死、前面还有交警查车——这些临时状况一出现，原本顺畅的路瞬间就废了，而大家没有任何感知。\n\n4. 校园路网复杂，很多人根本不知道该怎么绕\n桥、坡、生活区、教学区交错，两点之间不是直线简单走，而是藏着一堆“抄近道”。没有一张能算路的图，同学们只能靠“过来人经验”，很多时候绕了远路还更堵。', solution: '1. 用真实课表“算”出预测热度，而不是猜\n把全校课程表、宿舍分配和真实路网放在一起仿真，算出每条路、每个换课时段大概有多少人通行，生成一张会随星期和时刻变化的预测热度图——哪里会挤，提前就能看见。\n\n2. 真正的路网 + 三种走法的“个性化导航”\n基于 OpenStreetMap 的真实校园路网跑 Dijkstra（最短路算法），提供三种走法：\n\n走法\t干什么\n少人优先\t主动绕开高热度拥堵路段，走“人不挤”的路\n时间最短\t按实际骑行/步行时间求最快\n距离最短\t单纯看路程最短\n地点支持自动定位、58 个常用地点、或直接在地图上点选，谁都能会。\n\n3. 按“某天某节”预报，堵不堵分得清清楚楚\n能选具体日期 + 第1~10节，因为校园拥不拥堵和“星期几、第几节课”强相关——周三下午全校没课、周四晚上没人，和早上一二节完全两回事。终于分得出“这才叫堵，那只是正常”。\n\n4. 把特殊情况也算进来（情景推演）\n天气：联网获取，雨天自动减速、加重拥堵；\n封路：点一下就能封掉，流量自动重分配到替代路径，级联拥堵也能算；\n交警：标记后路线会自动绕开查车点；\n懂“堵的动态”：拥堵指数、新增堵点、受影响最重路段全网报告。\n5. 学生众包 + 管理员审核，让路况“实时”\n学生发现施工、事故、异常拥堵、有交警，点地图即可上报；\n管理员审核属实后才进入计算——既快又不被人乱带节奏；\n上报 6 小时自动失效，避免过时信息持续误导。',
    theme: 'Reimagine Campus', team: 'TEAM 09', year: '2026',
    tools: [], members: [{ name: '武政宇', role: null }, { name: '李俊霖', role: null }, { name: '武正航', role: null }],
    cover: null, coverAlt: '电动车大学跑路app 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-4213243D5F',
  },
  {
    id: '13', slug: 'project-13', title: '中南大学像素校园',
    description: '面向中南大学学生，方便学生使用查询，留下专属校园记忆',
    problem: '1. 课程信息查询不够便捷，学生需要反复查看课表，确认上课时间和地点，寻找感兴趣的课程也比较麻烦。\n2. 社团与活动信息分散在不同群聊和通知中，学生难以集中查找，容易错过感兴趣的活动。\n3. 校园照片散落在个人相册里，缺少一个与具体校园地点关联的空间，方便记录和重温大学生活。', solution: '以中南大学为原型，搭建了一座可探索、可交互的像素校园，把校园服务放进学生熟悉的地点中。\n\n1. 走到教学楼，进入课表与蹭课中心，录入或导入个人课表，查看课程安排，发现感兴趣的课程。\n2. 走到体育场，浏览社团目录与活动信息，按关键词和时间筛选，集中了解校园活动。\n3. 在图书馆、教学楼、体育场等地点上传和查看照片，让校园记忆与具体地点相连。\n4. 通过角色漫游、骑行和地点互动，让日常查询融入逛校园的过程，增加探索的乐趣和对校园的熟悉感。',
    theme: 'Reimagine Campus', team: 'TEAM 15', year: '2026',
    tools: ['Codex', 'Claude'], members: [{ name: '谢宏亿', role: '产品负责人' }, { name: '王佳一', role: '后端开发' }, { name: '顾蕊泽', role: '角色设计' }, { name: '晏丽颖', role: '前端开发' }, { name: '洪雅曦', role: '后端设计' }],
    cover: '/images/projects/project-13.jpg', coverAlt: '中南大学像素校园 作品封面', coverFull: null,
    repoUrl: 'https://github.com/td-xiehongyi/hackthon/tree/main', demoUrl: null,
    sourceId: 'PROJECT-FA2510E963',
  },
  {
    id: '14', slug: 'project-14', title: '小电驴的一天',
    description: '一款把大学生"骑小电驴上课"的日常难题做成闯关的像素风小游戏，从而起到教育大一新生的作用',
    problem: '在校园里骑电动车的同学每天都会遇到一串小麻烦：\n\n早上宿舍楼下车挤成一片，找不到自己的车，挪车还会带倒一排；\n上学路上人车混行，有外卖车、逆行车、横穿的行人，校外还可能碰上交警查头盔和牌照；\n教学楼车棚没车位，门口违停会被贴条；\n晚上充电桩被占、坏了、扫码失败，门禁前常常充不上电，第二天就只能推车迟到。\n\n这些问题很普遍，但平时很少有人认真聊，也很难让第一次在中南大学骑车的人体会到。', solution: '我们用 Phaser 3 做了一款网页小游戏，把这些真实场景做成一天里的几个关卡：宿舍楼下找车 → 骑车上学（躲避车流、应对交警）→ 车棚停车 → 中午吃饭或办牌照 → 晚上找桩充电。\n\n电量、钱、饥饿度和迟到次数会跨天累积，玩家要在省时间、省钱、守规矩之间做取舍。\n一共 6 个结局：3 个正常结局（完美、合格、不合格）和 3 个隐藏结局（被带去派出所、饿晕、身无分文）。\n浏览器打开就能玩，一局 5–10 分钟，用轻松的方式让大家看见校园出行的真实痛点，并引出对车位、充电桩和交通秩序的思考。',
    theme: 'Reimagine Campus', team: 'TEAM 16', year: '2026',
    tools: ['Claude Code', 'Codex'], members: [{ name: '周德诺', role: '产品负责人' }, { name: '林哲涵', role: '视觉设计' }, { name: '郭鸿毅', role: '视觉设计' }, { name: '古天豪', role: '前端开发' }],
    cover: '/images/projects/project-14.jpg', coverAlt: '小电驴的一天 作品封面', coverFull: null,
    repoUrl: 'https://github.com/godmiao760-afk/FedExing', demoUrl: null,
    sourceId: 'PROJECT-6D3ADA8766',
  },
  {
    id: '15', slug: 'project-15', title: '请勿喧哗',
    description: '《请勿喧哗》是一款用身体动作讲述“沟通”的互动叙事游戏：当玩家习惯用手势不断推动世界时，却会发现——有时停止动作，回应才会靠近。',
    problem: '我们习惯把“交互”理解为不断输入：点击、滑动、挥手、说话——做得越多，系统回应得越多。人与人的沟通也常陷入类似惯性：当我们急于表达、解释和解决问题时，反而可能忽略对方正在发出的回应。\n\n《请勿喧哗》希望探索一个反直觉的问题：如果“不操作”本身也可以成为一种有意义的交互呢？\n\n游戏将这种抽象的沟通体验转化为玩家亲自经历的过程：玩家最初被训练成不断使用手势推进剧情，却逐渐发现，越急于行动，世界反而离自己越远。真正的改变发生在玩家愿意停下来、观察并给对方留下回应空间的时候。', solution: '《请勿喧哗》是一款基于摄像头手势与运动状态识别的互动叙事游戏。我们没有简单地用手势替代鼠标，而是重新设计了“什么才算一次有效的操作”。\n\n游戏前期通过手势反馈建立“动作越多、推进越快”的操作习惯；进入深海后规则突然反转：玩家越用力挥手，鱼群越远；当玩家停止动作，水面逐渐平静，一条鱼先试探靠近，随后鱼群主动游回玩家身边。\n\n这一机制在结局再次出现，但意义发生变化：玩家停止动作后，不再是“触发机关”，而是另一名角色先主动伸出手，两人之间的阻隔随后消失。同一个“静止”，第一次改变游戏世界，第二次改变角色关系。\n\n技术上，系统通过摄像头实时识别玩家的手势与 MOVING / STILL 状态，并将连续运动状态直接映射到鱼群和环境反馈，再通过持续静止产生剧情事件。因此玩家的身体不仅是控制器，也成为叙事的一部分。\n\n我们希望创造的“Unexpected”，不是突然出现一个奇怪的东西，而是让玩家发现：自己一直认为理所当然的“操作方式”，本身也可以被重新设计。',
    theme: 'Create the Unexpected', team: 'TEAM 10', year: '2026',
    tools: ['Claude Code', 'ChatGPT'], members: [{ name: '韩思远', role: '项目负责人、核心开发、系统集成、交互逻辑' }, { name: '徐婕', role: '视觉设计、UI设计、场景美术、动效设计' }, { name: '刘阳', role: '手势识别、计算机视觉、交互技术支持' }, { name: '刘睿轩', role: '路演策划、PPT设计、项目展示与讲解' }, { name: '胡华凤', role: '用户感受测试、体验验证、剧情与交互测试' }],
    cover: '/images/projects/project-15.jpg', coverAlt: '请勿喧哗 作品封面', coverFull: null,
    repoUrl: 'https://github.com/Han-derp/PleaseBeQuiet', demoUrl: null,
    sourceId: 'PROJECT-5E213DE673',
  },
  {
    id: '16', slug: 'project-16', title: '中国龙能飞',
    description: '解决奶龙不会飞的问题，解决传统游戏交互方式沉浸感低的问题',
    problem: '传统游戏交互方式主要为键鼠和手柄，游戏的体验沉浸感较低，VR设备沉浸感强，但成本较高，不利于个人购买来玩', solution: '通过身体动作优化了游戏的互动体验',
    theme: 'Create the Unexpected', team: 'TEAM 11', year: '2026',
    tools: ['Codex'], members: [{ name: '陈一鸣', role: '产品负责人 规划设计分工 开发和路演' }, { name: '肖子涵', role: '产品设计和开发' }, { name: '肖贞怡', role: '视觉设计 PPT设计' }, { name: '辛俐庆', role: '前端开发 产品展示录制' }, { name: '古钰蓥', role: '产品开发主要负责人' }],
    cover: '/images/projects/project-16.jpg', coverAlt: '中国龙能飞 作品封面', coverFull: null,
    repoUrl: 'https://github.com/Eurin-gu/FLY-NaiLong', demoUrl: 'https://flylong666.netlify.app/',
    sourceId: 'PROJECT-CC04C0584E',
  },
  {
    id: '17', slug: 'project-17', title: '智能衣柜与家庭物品管理助手',
    description: '用 AI 帮助用户整理衣物、管理家庭物品，并快速获得穿搭建议。',
    problem: '用户常常记不清衣物和物品放在哪里，也难以根据天气、季节和已有衣物快速选择穿搭。传统记录方式操作繁琐，无法利用图片识别和智能推荐减少整理与决策时间。', solution: '我们开发了一个可在浏览器运行的智能衣柜与家庭空间管理应用。用户可以上传衣物图片，手动或通过 AI 记录名称、类别、颜色、材质和季节，并在房间网格中管理物品位置。系统结合天气信息和当前衣柜生成穿搭建议，同时支持搜索、筛选、JSON 导入和本地数据保存，帮助用户更快找到物品并完成每日穿搭选择。',
    theme: 'Create the Unexpected', team: 'TEAM 12', year: '2026',
    tools: ['Codex'], members: [{ name: '成雨珈', role: '产品负责人、项目策划、整体功能设计' }, { name: '周雨轩', role: '前端开发、页面交互与视觉设计' }, { name: '郑梓淇', role: '后端开发，后端开发' }, { name: '王福炜', role: 'API 与数据库功能，本地服务部署与测试' }],
    cover: null, coverAlt: '智能衣柜与家庭物品管理助手 作品封面', coverFull: null,
    repoUrl: 'https://github.com/Echorainy/Item-Storage-app', demoUrl: null,
    sourceId: 'PROJECT-032EB6537D',
  },
  {
    id: '18', slug: 'project-18', title: '因花寺',
    description: '一段关于选择、愿望与现实行动的沉浸式数字寺庙体验',
    problem: '为那些正在犹豫、曾经后悔的人们，找一个安静空间重新听见自己。', solution: '把人面对选择时的犹豫、愿望和后悔转化成一次可参与、可表达、可修正，并最终能够回到现实行动的体验。',
    theme: 'Create the Unexpected', team: 'TEAM 14', year: '2026',
    tools: [], members: [{ name: '耿梦月', role: null }, { name: '程子傲', role: null }, { name: '姚舒文', role: null }, { name: '戴义果', role: null }],
    cover: null, coverAlt: '因花寺 作品封面', coverFull: null,
    repoUrl: null, demoUrl: 'https://yinhua-story.pocketbay.app/',
    sourceId: 'PROJECT-7FB68F3AA2',
  },
  {
    id: '19', slug: 'project-19', title: '宝子，你想茶出怎样的滋味？',
    description: '我们为追求个性表达和体验感的年轻消费者，解决传统茶饮“只能定制口味参数，却无法表达我是谁”的问题。',
    problem: '当前茶饮行业的个性化体验大多停留在糖度、冰量、小料等参数选择，消费者虽然拥有更多选择，却很难真正参与饮品创作，也缺少能够表达个人审美、情绪与当下状态的产品体验。尤其对于注重个性表达与社交分享的年轻消费者，一杯饮品不仅是口味消费，也承载着自我表达和情绪价值。我们希望解决传统茶饮“可以定制口味，却难以定制属于我的体验”这一痛点，让消费者从被动选择菜单，转变为饮品创作的参与者。', solution: '「宝子，你想茶出怎样的滋味？」是一套由 AI 与主理人共同完成的个性化饮品创作体验。用户提供一张代表当下状态的照片，系统从色彩、材质、穿搭、环境与情绪等维度提取“视觉 DNA”，并将视觉线索转译为茶底、奶沫、小料、风味与装饰等“风味 DNA”。AI 提供创作方向与可能性，再由主理人结合审美、口味与实际制作进行取舍，最终形成具有专属名称、配方、故事与寄语的个性化饮品。我们不是简单地根据照片生成一杯好看的奶茶，而是建立“视觉解读—风味转译—主理人取舍—专属成饮”的完整体验，让每一杯饮品都能回答：为什么这一杯属于你。',
    theme: 'Create the Unexpected', team: 'TEAM 22', year: '2026',
    tools: ['Codex'], members: [{ name: '黄一翰', role: '产品设计与所有开发' }],
    cover: null, coverAlt: '宝子，你想茶出怎样的滋味？ 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-29212EA450',
  },
  {
    id: '20', slug: 'project-20', title: '属于工程师的AI智能桌宠助手',
    description: '把AI和桌宠结合',
    problem: '简化AI使用流程', solution: '简化AI使用流程，使日常中的一些任务的处理流程得到简化，让工程开发与生活更加便捷。平时是桌宠图片，点击桌宠打开AI对话框',
    theme: null, team: 'TEAM 20', year: '2026',
    tools: ['Codex'], members: [{ name: '陈成一', role: null }, { name: '邱浩俊', role: null }, { name: '张淮博', role: null }, { name: '张宸瑾', role: null }, { name: '李春梅', role: null }],
    cover: null, coverAlt: '属于工程师的AI智能桌宠助手 作品封面', coverFull: null,
    repoUrl: null, demoUrl: null,
    sourceId: 'PROJECT-A920F953CB',
  },
];

export const moments = [
  { id: '01', src: null, alt: 'minicamp 活动现场', caption: '相遇的瞬间', theme: 'blue' },
  { id: '02', src: null, alt: 'minicamp 共创现场', caption: '一起动手的时候', theme: 'orange' },
  { id: '03', src: null, alt: 'minicamp 作品展示', caption: '想法被看见', theme: 'mint' },
  { id: '04', src: null, alt: 'minicamp 交流现场', caption: '新的连接', theme: 'sand' },
];
