import { guides, guideCategories, learningLinks } from '../content/guides.mjs';
import { esc, eyebrow, pageLink, joinSection, shareButton } from './components.mjs';
import { programIcon } from './community.mjs';

export const guidePath = guide => `/resources/${guide.slug}/`;
const guideCard = guide => `<article class="guide-card guide-${guide.tone}" data-filter-item data-category="${guide.category}" data-search="${esc([guide.title,guide.shortTitle,guide.description,guide.tag,...guide.sections.map(s=>s.title)].join(' '))}" data-detail-surface><div class="guide-cover" aria-hidden="true"><span class="mono">NANOCAMP / FIELD GUIDE</span><b>${guide.number}</b><span class="guide-cover-icon">${programIcon(guide.icon)}</span><i></i></div><div class="guide-card-body"><div class="guide-card-meta"><span>${guide.tag}</span><span>指南 + 实用模板</span></div><h3><a href="${guidePath(guide)}">${esc(guide.shortTitle)}<span aria-hidden="true">↗</span></a></h3><p>${esc(guide.description)}</p><a class="text-link" href="${guidePath(guide)}">翻开这份指南</a></div></article>`;

export function resourcesPage() {
  return `<section class="page-hero container resource-hero"><div>${eyebrow('A LITTLE HELP FOR YOUR NEXT BIG IDEA.')}<h1>想做点什么？<br>从这一页<span class="blue-text">开始。</span></h1><p class="page-subtitle">找队友、做原型、讲 Demo、发起分享。<br>翻开一份指南，带走模板，边读边做。</p></div><div class="resource-stack" aria-hidden="true"><span class="stack-sheet sheet-back"></span><span class="stack-sheet sheet-middle"></span><div class="stack-sheet sheet-front"><span class="mono">FIELD NOTES</span>${programIcon('build')}<strong>START<br>SOMETHING.</strong><span class="stack-label">好奇心使用手册</span><span class="stack-corner">✳</span></div></div></section>
  <section class="container section resource-library" data-directory="resources" aria-labelledby="library-title"><div class="section-top"><div>${eyebrow('READ A LITTLE. TRY A LITTLE.', '01')}<h2 id="library-title">选一份，边读边做。</h2></div><p class="section-description">先选你现在想做的事。<br>每份指南都有步骤、检查清单和文本模板。</p></div><div class="resource-toolbar"><div class="filter-bar" role="group" aria-label="筛选指南主题" data-filter-controls hidden>${guideCategories.map(([id,name])=>`<button type="button" data-filter="${id}" aria-pressed="${id==='all'}">${name}</button>`).join('')}</div><div data-search-controls hidden><label class="sr-only" for="resource-search">搜索指南</label><div class="search-field"><span aria-hidden="true">⌕</span><input type="search" id="resource-search" data-search-input placeholder="搜索想法、组队、分享…" maxlength="120" autocomplete="off"><button type="button" data-search-clear aria-label="清空搜索" hidden>×</button></div></div></div><p class="filter-status" data-filter-status role="status" aria-live="polite" hidden></p><div class="guide-grid">${guides.map(guideCard).join('')}</div><div class="directory-empty" data-filter-empty hidden><span aria-hidden="true">?</span><h2>换一个起点试试。</h2><p>暂时没有匹配的指南，可以清除筛选后重新选择。</p><button class="button button-secondary" type="button" data-filter-reset>查看全部指南</button></div></section>
  <section class="learning-section" aria-labelledby="learning-title"><div class="container section"><div class="section-top"><div>${eyebrow('KEEP EXPLORING', '02')}<h2 id="learning-title">带着问题，继续探索。</h2></div><p class="section-description">遇到具体问题时，去官方文档找线索。<br>下方链接会在新标签页打开。</p></div><div class="learning-links">${learningLinks.map((item,i)=>`<a class="learning-link" href="${esc(item.href)}" target="_blank" rel="noopener noreferrer"><span class="learning-index mono">0${i+1}</span><div><span class="mono learning-source">${item.from}</span><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><span class="learning-language">${item.label}</span></div><span class="learning-arrow" aria-hidden="true">↗</span><span class="sr-only">（新标签页打开）</span></a>`).join('')}</div></div></section><section class="container community-help resource-invitation"><div><span class="mono">KNOW SOMETHING WORTH SHARING?</span><h2>你的一次发现，也可以是别人的起点。</h2><p>带着一个具体主题，来发起下一次交流。</p></div>${pageLink('/community/#share','了解分享方式')}</section>${joinSection(true)}`;
}

export function guidePage(guide) {
  const next = guides.find(item => item.slug === guide.next);
  return `<div class="container guide-breadcrumb"><a href="/resources/">共创资源</a><span aria-hidden="true">/</span><span>${esc(guide.shortTitle)}</span></div><header class="container guide-hero"><div class="guide-kicker"><span class="guide-tag">${guide.tag}</span><span class="mono">共创指南 / ${guide.number}</span></div><h1>${esc(guide.title)}</h1><p>${esc(guide.description)}</p><div class="guide-takeaway"><span aria-hidden="true">↳</span>${esc(guide.takeaway)}</div></header>
  <div class="container guide-layout"><aside class="guide-sidebar" aria-label="这份指南的目录"><div class="guide-toc"><span class="mono">本篇目录</span><nav aria-label="文章目录">${guide.sections.map((s,i)=>`<a href="#${s.id}"><span class="mono">0${i+1}</span>${esc(s.title)}</a>`).join('')}<a href="#prepare"><span aria-hidden="true">✓</span>准备清单</a><a href="#template"><span aria-hidden="true">↓</span>带走模板</a></nav><p>不必一次做好全部。<br>选一个小动作，从现在开始。</p>${shareButton('复制指南链接')}<a href="/resources/" class="text-link">返回资源中心</a></div></aside><article class="guide-body">${guide.sections.map((section,i)=>`<section id="${section.id}" class="guide-section"><span class="guide-section-index mono">0${i+1}</span><h2>${esc(section.title)}</h2>${section.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${section.bullets?`<ul class="guide-bullets">${section.bullets.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${section.prompt?`<div class="guide-prompt"><span class="mono">试着写一句</span><p>${esc(section.prompt)}</p></div>`:''}</section>`).join('')}
    <section id="prepare" class="preparation-checklist" data-checklist="${guide.slug}" aria-labelledby="prepare-heading"><div class="checklist-heading"><div><span class="mono">准备清单</span><h2 id="prepare-heading">准备到哪一步了？</h2></div><span class="checklist-spark" aria-hidden="true">✳</span></div><div class="checklist-progress" data-check-enhanced hidden><div><span data-check-count role="status" aria-live="polite">已完成 0 / ${guide.checklist.length}</span><button type="button" data-check-reset>清空勾选</button></div><progress max="${guide.checklist.length}" value="0" aria-label="准备清单完成度"></progress></div><ul>${guide.checklist.map((text,i)=>`<li><label><input type="checkbox" value="item-${i+1}"><span class="check-box" aria-hidden="true"></span><span>${esc(text)}</span></label></li>`).join('')}</ul><p class="checklist-save-note" data-check-save hidden></p></section>
    <section id="template" class="guide-template" aria-labelledby="template-heading"><div class="template-heading"><div><span class="mono">带走模板</span><h2 id="template-heading">${esc(guide.template.split("\n")[0])}</h2></div></div><p>复制到你和伙伴共用的文档，填下这一轮的想法与约定。也可以下载后慢慢整理。</p><div class="template-actions"><button class="button button-secondary" type="button" data-template-copy hidden>复制模板 <span aria-hidden="true">⧉</span></button><a class="button button-secondary" href="/downloads/${guide.slug}-template.txt" download="NanoCamp-${guide.slug}.txt">下载文本模板 <span aria-hidden="true">↓</span></a></div><p class="tool-status" role="status" aria-live="polite" data-template-status></p><pre class="template-paper" data-template-text tabindex="-1">${esc(guide.template)}</pre></section>
  </article></div>
  <section class="container guide-next"><span class="mono">继续探索</span><div><h2>下一页，继续动手。</h2><a href="${guidePath(next)}">${esc(next.shortTitle)}<span aria-hidden="true">↗</span></a></div></section>${joinSection(true)}`;
}