export function recapNavigation() {
  const chapters=[['recap','01','活动回顾'],['camp-projects','02','共创作品'],['keep-building','03','继续共创']];
  return `<nav class="recap-nav" data-recap-nav aria-label="minicamp 回顾章节"><div class="container recap-nav-inner"><span class="recap-nav-note mono"><i aria-hidden="true"></i>CHAPTER 01</span><div class="recap-nav-links">${chapters.map(([id,number,label])=>`<a href="#${id}"><span class="mono" aria-hidden="true">${number}</span><span>${label}</span><i aria-hidden="true"></i></a>`).join('')}</div></div></nav>`;
}
export function galleryDialog() {
  const arrow=direction=>`<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="${direction==='prev'?'M19 12H5m6-6-6 6 6 6':'M5 12h14m-6-6 6 6-6 6'}"/></svg>`;
  return `<dialog id="lightbox-dialog" class="lightbox-dialog album-dialog" aria-labelledby="lightbox-title" aria-describedby="lightbox-help">
    <header class="album-topbar"><div><span class="album-kicker mono" aria-hidden="true"><i></i>NANOCAMP / MOMENTS</span><h2 id="lightbox-title">现场相册</h2></div><span class="album-counter mono" data-photo-count aria-hidden="true"></span><button type="button" class="dialog-close" data-close-dialog aria-label="关闭照片相册" autofocus>×</button></header>
    <div class="album-stage" data-photo-stage tabindex="-1" aria-label="照片浏览区域" aria-busy="false"><button class="album-arrow album-prev" type="button" data-photo-prev aria-label="上一张照片" hidden>${arrow('prev')}</button><div class="album-canvas"><img id="lightbox-image" class="album-photo" alt="" decoding="async" draggable="false" hidden><div class="album-loading" data-photo-loading role="status" hidden><span class="photo-loader" aria-hidden="true"><i></i><i></i><i></i></span><span>正在打开这一刻…</span></div><div class="album-error" data-photo-error hidden><span aria-hidden="true">↻</span><h3>这一张，暂时没有打开。</h3><p>可以重新加载，或继续看看其他照片。</p><button class="button button-secondary" type="button" data-photo-retry>重新加载 <span aria-hidden="true">↗</span></button></div></div><button class="album-arrow album-next" type="button" data-photo-next aria-label="下一张照片" hidden>${arrow('next')}</button></div>
    <div class="album-caption-row"><p id="lightbox-caption"></p><a class="album-original" data-photo-original target="_blank" rel="noopener noreferrer">打开原图 <span aria-hidden="true">↗</span><span class="sr-only">（新标签页打开）</span></a></div>
    <div class="album-bottom"><p id="lightbox-help">方向键切换照片，Esc 关闭相册。</p><span class="album-swipe-note" aria-hidden="true">左右滑动，继续看。</span></div><p class="sr-only" role="status" aria-live="polite" data-photo-status></p><div class="album-thumbnails" data-photo-thumbnails role="group" aria-label="选择照片" hidden></div>
  </dialog>`;
}